# Generated by Django 4.2.13 on 2026-09-10 00:00

from django.db import migrations, models


def set_superadmin_role(apps, schema_editor):
    """Asignar rol='superadmin' a los superusuarios existentes."""
    CustomUser = apps.get_model("accounts", "CustomUser")
    CustomUser.objects.filter(is_superuser=True).update(rol="superadmin")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="rol",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Administrador"),
                    ("admin", "Administrador"),
                    ("tecnico", "Técnico"),
                    ("lectura", "Solo lectura"),
                ],
                default="tecnico",
                max_length=20,
            ),
        ),
        migrations.RunPython(set_superadmin_role, migrations.RunPython.noop),
    ]