# Generated by Django 4.2.13 on 2026-09-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0005_activo_catalogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenciaSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Software')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Versión')),
                ('proveedor', models.CharField(blank=True, max_length=120, verbose_name='Proveedor / editor')),
                ('clave', models.CharField(blank=True, max_length=255, verbose_name='Clave / serial')),
                ('tipo', models.CharField(choices=[('volumen', 'Volumen'), ('individual', 'Individual'), ('oem', 'OEM / Preinstalada'), ('suscripcion', 'Suscripción')], default='volumen', max_length=20, verbose_name='Tipo de licencia')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad (usuarios / equipos)')),
                ('fecha_compra', models.DateField(blank=True, null=True, verbose_name='Fecha de compra')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('por_vencer', 'Por vencer'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('responsable', models.CharField(blank=True, max_length=120)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activos', models.ManyToManyField(blank=True, related_name='licencias', to='inventario.activo', verbose_name='Equipos cubiertos')),
            ],
            options={
                'verbose_name': 'Licencia de software',
                'verbose_name_plural': 'Licencias de software',
                'ordering': ['nombre', 'version'],
            },
        ),
    ]
