# Generated by Django 4.2.13 on 2026-09-10 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='REDIHOS S.A.S', max_length=150, verbose_name='Nombre de la empresa')),
                ('nit', models.CharField(blank=True, max_length=20, verbose_name='NIT')),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email_contacto', models.EmailField(blank=True, max_length=254, verbose_name='Correo de contacto')),
                ('pie_firma_reporte', models.CharField(blank=True, default='Departamento de Sistemas', max_length=200, verbose_name='Firma de reportes')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'verbose_name_plural': 'Configuración del sistema',
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('usuarios', 'Usuarios'), ('inventario', 'Inventario'), ('mantenimiento', 'Mantenimiento'), ('passwords', 'Passwords'), ('reportes', 'Reportes'), ('documentos', 'Documentos'), ('administracion', 'Administracion'), ('auth', 'Inicio de sesión')], max_length=30)),
                ('accion', models.CharField(max_length=30)),
                ('objeto_tipo', models.CharField(blank=True, max_length=60, verbose_name='Tipo de objeto')),
                ('objeto_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID del objeto')),
                ('detalle', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['modulo', 'fecha'], name='administrac_modulo_dcade8_idx'), models.Index(fields=['usuario', 'fecha'], name='administrac_usuario_8d4bb0_idx')],
            },
        ),
    ]
