# Generated by Django 4.2.13 on 2026-09-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='modulo',
            field=models.CharField(choices=[('usuarios', 'Usuarios'), ('inventario', 'Inventario'), ('mantenimiento', 'Mantenimiento'), ('passwords', 'Passwords'), ('reportes', 'Reportes'), ('documentos', 'Documentos'), ('administracion', 'Administracion'), ('soporte', 'Soporte'), ('licencias', 'Licencias'), ('prestamos', 'Prestamos'), ('auth', 'Inicio de sesión')], max_length=30),
        ),
    ]
