# Generated by Django 4.2.13 on 2026-09-23 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='area_solicitante',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Área o departamento'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='contacto_solicitante',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Correo o extensión de contacto'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='nombre_solicitante',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Nombre del solicitante'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
    ]
