# Generated by Django 4.2.13 on 2026-09-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0002_ticket_area_solicitante_ticket_contacto_solicitante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='acciones_realizadas',
            field=models.TextField(blank=True, default='', verbose_name='Acciones realizadas'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='numero_serie_etiqueta',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Número de serie o etiqueta del equipo'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tiempo_empleado_minutos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tiempo empleado (minutos)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipo_dispositivo',
            field=models.CharField(blank=True, choices=[('celular', 'Celular'), ('escritorio', 'Equipo Escritorio'), ('portatil', 'Portátil'), ('telefono_fijo', 'Teléfono Fijo'), ('monitor', 'Monitor')], default='', max_length=50, verbose_name='Tipo de dispositivo'),
        ),
    ]
