PARTES_POR_TIPO = {
    "celular": [
        ("pantalla", "Pantalla"),
        ("bateria", "Batería"),
        ("camara", "Cámara"),
        ("puerto_carga", "Puerto de carga"),
        ("boton_encendido", "Botón de encendido"),
        ("parlantes", "Parlantes"),
        ("microfono", "Micrófono"),
    ],
    "escritorio": [
        ("disco_duro", "Disco duro"),
        ("memoria_ram", "Memoria RAM"),
        ("ventilador", "Ventilador/cooler"),
        ("placa_base", "Placa base"),
        ("puertos", "Puertos"),
        ("fuente_poder", "Fuente de poder"),
        ("red_wifi", "Red/WiFi"),
        ("boton_encendido", "Botón de encendido"),
        ("carcasa", "Carcasa"),
    ],
    "portatil": [
        ("pantalla", "Pantalla"),
        ("teclado", "Teclado"),
        ("touchpad", "Touchpad"),
        ("bateria", "Batería"),
        ("disco_duro", "Disco duro"),
        ("memoria_ram", "Memoria RAM"),
        ("ventilador", "Ventilador/cooler"),
        ("placa_base", "Placa base"),
        ("puertos", "Puertos"),
        ("cargador", "Cargador"),
        ("bisagras", "Bisagras"),
        ("camara", "Cámara"),
        ("parlantes", "Parlantes"),
        ("wifi", "WiFi"),
        ("boton_encendido", "Botón de encendido"),
        ("carcasa", "Carcasa"),
    ],
    "telefono_fijo": [
        ("auricular", "Auricular/parlante"),
        ("teclado", "Teclado"),
        ("cable", "Cable"),
        ("boton_encendido", "Botón de encendido"),
    ],
    "monitor": [
        ("pantalla", "Pantalla"),
        ("puerto_video", "Puerto de video"),
        ("boton_encendido", "Botón de encendido"),
        ("carcasa", "Carcasa"),
    ],
}
