# Generated by Django 4.2.13 on 2026-09-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yule', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='equipoocs',
            new_name='yule_equipo_id_ocs_22831e_idx',
            old_name='yule_equipo_id_ocs_idx',
        ),
        migrations.RenameIndex(
            model_name='equipoocs',
            new_name='yule_equipo_nombre__8c5e03_idx',
            old_name='yule_equipo_nombre_host_idx',
        ),
        migrations.RenameIndex(
            model_name='equipoocs',
            new_name='yule_equipo_mac_add_83cf04_idx',
            old_name='yule_equipo_mac_address_idx',
        ),
        migrations.RenameIndex(
            model_name='equipoocs',
            new_name='yule_equipo_activo__2dd906_idx',
            old_name='yule_equipo_activo_local_idx',
        ),
    ]
