# Generated by Django 4.2.13 on 2026-09-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yule', '0002_rename_yule_equipo_id_ocs_idx_yule_equipo_id_ocs_22831e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionyule',
            name='integracion_activa',
            field=models.BooleanField(default=True, verbose_name='Integración activa'),
        ),
        migrations.AddField(
            model_name='configuracionyule',
            name='password_cifrada',
            field=models.TextField(blank=True, default='', verbose_name='Contraseña OCS'),
        ),
        migrations.AddField(
            model_name='configuracionyule',
            name='url',
            field=models.URLField(blank=True, default='', help_text='Ej.: https://srv.ocs.redihos.local:8443/ocsapi/v1', max_length=300, verbose_name='URL OCS'),
        ),
        migrations.AddField(
            model_name='configuracionyule',
            name='usuario',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Usuario OCS'),
        ),
    ]
