# Generated by Django 4.2.13 on 2026-05-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='catalogomodelo',
            name='unique_catalogo_tipo_marca_modelo',
        ),
        migrations.AlterField(
            model_name='actaasignacion',
            name='pdf_generado',
            field=models.FileField(blank=True, null=True, upload_to='inventario/actas/pdf/'),
        ),
        migrations.AlterUniqueTogether(
            name='catalogomodelo',
            unique_together={('tipo_dispositivo', 'marca', 'modelo')},
        ),
    ]
