# Generated by Django 4.2.13 on 2026-09-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_catalogomodelo_unique_catalogo_tipo_marca_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('ingreso', 'Ingreso'),
                    ('egreso', 'Egreso'),
                    ('traslado', 'Traslado'),
                    ('devolucion', 'Devolución'),
                    ('baja', 'Baja'),
                    ('asignacion', 'Asignación'),
                ],
                max_length=20,
            ),
        ),
    ]
