# Generated by Django 4.2.13 on 2026-09-11 18:10

from django.db import migrations, models


def asignar_numero_interno(apps, schema_editor):
    Activo = apps.get_model("inventario", "Activo")
    numero = 999
    for activo in Activo.objects.order_by("fecha_creacion", "pk"):
        numero += 1
        activo.numero_interno = numero
        activo.save(update_fields=["numero_interno"])


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0005_activo_catalogo"),
    ]

    operations = [
        migrations.AddField(
            model_name="activo",
            name="numero_interno",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.RunPython(asignar_numero_interno, migrations.RunPython.noop),
    ]