# Generated by Django 4.2.13 on 2026-09-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_activo_numero_interno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='tipo_dispositivo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='catalogomodelo',
            name='tipo_dispositivo',
            field=models.CharField(max_length=50),
        ),
    ]
