# Generated by Django 4.2.13 on 2026-09-29 13:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_asignacion_accesorios_condicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareInstalado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=255)),
                ('version', models.CharField(blank=True, default='', max_length=255)),
                ('fabricante', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_instalacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Detectado por primera vez')),
                ('fecha_ultima_vista', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Visto por última vez')),
                ('fecha_retiro', models.DateTimeField(blank=True, null=True, verbose_name='Dejó de reportarse')),
                ('presente', models.BooleanField(default=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_instalado', to='inventario.activo', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Software instalado',
                'verbose_name_plural': 'Software instalado',
                'ordering': ['nombre', 'version'],
                'indexes': [models.Index(fields=['nombre', 'presente'], name='inventario__nombre_59c187_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='softwareinstalado',
            constraint=models.UniqueConstraint(fields=('activo', 'nombre', 'version'), name='uniq_software_por_activo_nombre_version'),
        ),
    ]
