# Generated by Django 4.2.13 on 2026-09-10 18:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0005_activo_catalogo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(default=datetime.date.today, verbose_name='Fecha de préstamo')),
                ('fecha_devolucion_prevista', models.DateField(blank=True, null=True, verbose_name='Devolución prevista')),
                ('fecha_devolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de devolución')),
                ('destino', models.CharField(blank=True, max_length=200, verbose_name='Destino / motivo')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='inventario.activo', verbose_name='Equipo')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo', '-fecha_creacion'],
                'indexes': [models.Index(fields=['fecha_prestamo', 'fecha_devolucion_prevista'], name='prestamos_p_fecha_p_64d364_idx')],
            },
        ),
    ]
