# Generated by Django 4.2.13 on 2026-09-10 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmantenimiento',
            name='criticidad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('en_proceso', 'En proceso'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada'), ('reportada', 'Reportada')], default='abierta', max_length=20),
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('completado', models.BooleanField(default=False)),
                ('posicion', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='mantenimiento.ordenmantenimiento', verbose_name='Orden (copia)')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='mantenimiento.planmantenimiento', verbose_name='Plan (plantilla)')),
            ],
            options={
                'verbose_name': 'Ítem de checklist',
                'verbose_name_plural': 'Ítems de checklist',
                'ordering': ['posicion', 'id'],
            },
        ),
    ]
