# Generated by Django 4.2.13 on 2026-09-10 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0001_initial'),
        ('mantenimiento', '0002_planmantenimiento_criticidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='soporte.ticket', verbose_name='Ticket de soporte'),
        ),
    ]
