# Generated by Django 4.2.13 on 2026-09-11 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mantenimiento', '0003_ordenmantenimiento_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='reportado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_reportadas', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por'),
        ),
    ]
