# Generated by Django 4.2.13 on 2026-09-15 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0005_ordenmantenimiento_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='software_snapshot',
            field=models.JSONField(blank=True, default=list, verbose_name='Software instalado (snapshot OCS)'),
        ),
        migrations.CreateModel(
            name='FotoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='mantenimiento/fotos/', verbose_name='Foto')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='mantenimiento.ordenmantenimiento')),
            ],
            options={
                'verbose_name': 'Foto de mantenimiento',
                'verbose_name_plural': 'Fotos de mantenimiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
