# Generated by Django 4.2.13 on 2026-09-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0007_plan_tipo_dispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='accion_cambio_parte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='accion_cambio_parte_detalle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='accion_cambio_pasta_termica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='accion_limpieza_general',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='accion_mantenimiento_logico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='estado_partes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
