# Generated by Django 4.2.13 on 2026-09-10 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('garantia', 'Garantía'), ('mantenimiento', 'Mantenimiento'), ('acta', 'Acta de asignación'), ('ocs', 'Equipos OCS'), ('aviso', 'Aviso del sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('objetokey', models.CharField(blank=True, max_length=150)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'leida', 'fecha_creacion'], name='notificacio_usuario_a20953_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='notificacion',
            constraint=models.UniqueConstraint(condition=models.Q(('objetokey', ''), _negated=True), fields=('usuario', 'tipo', 'objetokey'), name='uniq_notificacion_objeto'),
        ),
    ]
