# Generated by Django 4.2.13 on 2026-09-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('garantia', 'Garantía'), ('mantenimiento', 'Mantenimiento'), ('acta', 'Acta de asignación'), ('ocs', 'Equipos OCS'), ('licencia', 'Licencias / contratos'), ('aviso', 'Aviso del sistema')], max_length=20),
        ),
    ]
